### ISSUE TITLE
start month is off

### ISSUE THREAD

**Issue by sdetweil** [bibaldo/MMM-CountUP#3]
javascript date and moment use 0-11 as month..

so 2020-03-16 means april, not march
after converting from string to date, subtract 1 month

**Comment by Bromley47** [comment]
{

                        module: "MMM-CountUP",
                        position: "top_bar",
                        config: {
                        header: "Days passed since COVID19 Quarantine",
                        date: "2020-02-16",
                        time: "09:00:00"

Tried the above but still showing 2 days

**Comment by Bromley47** [comment]
which I assume is days passed since April 16th.?

**Comment by elgeorgie** [comment]
Same issue here.  Month is off.

**Comment by sdetweil** [comment]
@elgeorgie  use from my repo.. when just showing the days ... the calculator doesn't use the years/months.. 

https://github.com/sdetweil/MMM-CountUP
rename the existing out of the way, then git clone mine and restart MM

**Comment by elgeorgie** [comment]
> @elgeorgie use from my repo.. when just showing the days ... the calculator doesn't use the years/months..
> 
> https://github.com/sdetweil/MMM-CountUP
> rename the existing out of the way, then git clone mine and restart MM

Works like a charm!  Thanks @sdetweil !!

**Comment by bibaldo** [comment]
@sdetweil thanks for your PR. It was merged today. I was off during these days.


@elgeorgie you can still use this repo if you like. It's up-to-date now
